apiVersion: v1
appVersion: "1.0"
description: "dia-webhook"
name: diawh
version: 1.0.0
dependencies:
  - name: cert-manager
    version: 1.10.1
    repository: "https://charts.jetstack.io/"
    condition: webhookTLS.installCertManager
    alias: cert-manager
