apiVersion: apps/v1
kind: Deployment
metadata:
  name: dia-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: "diawh"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "diawh"
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: dia-webhook
        env:
          {{ .Values.env | toYaml |nindent 11 }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/pki/tls/certs/ca.pem
          subPath: ca.crt
          name: dia-attestor-ca
        - mountPath: /etc/pki/tls/certs/diawh.crt
          subPath: tls.crt
          name: dia-tls-v
        - mountPath: /etc/pki/tls/private/diawh.key
          subPath: tls.key
          name: dia-tls-v
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      serviceAccount: diawh
      volumes:
      - secret:
          secretName: dia-attestor-ca
        name: dia-attestor-ca
      - secret:
      {{ if .Values.webhookTLS.useCertManager }}
          secretName: dia-tls-cert
      {{- else }}
          secretName: {{ .Values.webhookTLS.secretName }}
      {{- end }}
        name: dia-tls-v
