{{- if not .Values.attestor_ca }}
{{- fail "attestor_ca not found in Values, requred" }}
{{- else }}
kind: Secret
apiVersion: v1
metadata:
  name: dia-attestor-ca
data:
  ca.crt: >-
    {{ .Values.attestor_ca }}
type: Opaque
{{- end }}
