---
apiVersion: v1
kind: Service
metadata:
  name: diawh
  labels:
    app.kubernetes.io/name: "diawh"
spec:
  type: ClusterIP
  ports:
   - name: http-port
     port: 8080
     targetPort: 8080
  selector:
    app.kubernetes.io/name: "diawh"
